// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbnxbxnapcsjttlbehyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibnhieG5hcGNzanR0bGJlaHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjkwMTEsImV4cCI6MjA1ODgwNTAxMX0.JLY6qCB6k50YwBx2DFiBIOGb713QDjgi_8BRK2mN2Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);